name: 'Publish with tag action'
description: 'Publish npm packages on releases.'
outputs:
  version:
    description: 'The version that was published'
  tag:
    description: 'The tag that was used to publish'
runs:
  using: 'node12'
  main: 'dist/bundle.js'
