name: 'Publish With tag'
description: 'Publish an npm package under the correct tag when using a workflow triggered by a release. The release version must follow semver.'
outputs:
  version:
    description: 'The version that was published'
  tag:
    description: 'The tag that was used to publish'
runs:
  using: 'node12'
  main: 'dist/bundle.js'
